[build]
builder = "NIXPACKS"

[deploy]
# Install Railway-specific requirements and start the API server
startCommand = "pip install -r requirements-railway.txt && uvicorn api_server:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Railway-specific environment
[environment]
RAILWAY = "true"
